import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { HeaderWrapper } from "./components/Headers/HeaderWrapper";
import { BsWhatsapp } from "react-icons/bs";

const inter = Inter({
  variable: "--font-inter",
  subsets: ["latin"],
  weight: ["100", "200", "300", "400", "500", "600", "700", "800", "900"],
});

export const metadata: Metadata = {
  title: "SMK Tamtama Kroya",
  description: "Generated by create next app",
  icons: {
    icon: "/favicon.ico",
  },
};

const message =
  "Halo, tolong infokan terkait pendaftaran di SMK Tamtama Kroya ";
const encodedMessage = encodeURIComponent(message);

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} antialiased`}>
        <HeaderWrapper />
        {children}
        <a
          href={`https://wa.me/6281325767718?text=${encodedMessage}`}
          target="_blank"
          rel="noopener noreferrer"
          className="fixed z-50 drop-shadow-xl bottom-4 md:right-8 right-2 bg-[#25d366] p-2 md:mr-4 md:mb-8 rounded-full flex items-center justify-center hover:scale-105 transition-transform"
        >
          <BsWhatsapp size={30} color="white" />
        </a>
      </body>
    </html>
  );
}
